### ISSUE TITLE
아이템 기획하기

### ISSUE THREAD

**Issue by JesungKoo** [JesungKoo/ng2p#1]
가칭: 요즘 할 게임 없네

1. 실제 어떤 기능을 구현할지 정리
2. README.md 변경
3. 화면설계서와 기능명세서 작성 [관련 글](https://medium.com/@mklab.co/%EC%9E%91%EC%84%B1%EB%B2%95-%ED%99%94%EB%A9%B4%EC%84%A4%EA%B3%84%EC%84%9C-wireframe-%EC%99%80-%EA%B8%B0%EB%8A%A5%EB%AA%85%EC%84%B8%EC%84%9C-functional-specification-bbcff0071ea2)

**Comment by JesungKoo** [comment]
핵심 기능: 문자열 입력시, 해당 문자열에 가장 근접한 게임 출력

**Comment by codingHack** [comment]
재밌겠다

**Comment by JesungKoo** [comment]
> 재밌겠다

너도 같이 할래?

**Comment by codingHack** [comment]
ㅇㅇ

**Comment by JesungKoo** [comment]
> ㅇㅇ 근데갑앵귤러?

앵귤러 공부하면서 토이프로젝트로 시작함ㅋㅋㅋ

**Comment by WinteringAsch** [comment]
[ng2p.zip](https://github.com/JesungKoo/ng2p/files/3803688/ng2p.zip)
처음 써보는거라 뭐가 뭔지 모르겠군...

**Comment by JesungKoo** [comment]
https://forums.balsamiq.com/t/version-control-for-desktop-app/6066/6
balsamiq Desktop의 경우 버전관리가 어려운듯. 클라우드 서비스 사용하는 것으로?

**Comment by WinteringAsch** [comment]
https://balsamiq.cloud/smkbrd5/pxc8l2d/r5D9A
